### ISSUE TITLE
Support for PHP 8.1 or 8.2

### ISSUE THREAD

**Issue by jeremyljohnson** [VirgilSecurity/virgil-cryptowrapper-php#8]
My client is using your crypto wrapper extension in a production environment with thousands of users running on PHP 8.0.  Considering that active support for 8.0 ended in November, and security support will only last for the next 3 months, do you have plans to release your crypto wrapper for PHP 8.1 or 8.2 in the next few months?

Or if we can use the PHP 8.0 extension in a PHP 8.1 or 8.2 environment, perhaps you can update the documentation, as I'm sure I'm not the only one looking for support for more modern PHP releases?

**Comment by SergeySeroshtan** [comment]
https://github.com/VirgilSecurity/virgil-cryptowrapper-php/releases/tag/v0.17.1
